
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WINDOWS 10
 */
public class pertemuan6 extends javax.swing.JFrame {
    String daftar_pesanan= "";
    int totalSemua=0;
    /**
     * Creates new form pertemuan6
     */
    public pertemuan6() {
        initComponents();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup1.add(tempat_radio);
        buttonGroup1.add(pulang_radio);
        
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup2.add(kasir_radio); 
        buttonGroup2.add(qris_radio);
        
        SimpleDateFormat sdf=new SimpleDateFormat("dd/mm/yyyy");
        Date date = new Date();
        tanggal_field.setText(sdf.format(date));
        tanggal_field.setEditable(false);
        
        dropdown_kategori.removeAllItems();
        dropdown_kategori.addItem("Makanan");
        dropdown_kategori.addItem("Snack");
        dropdown_kategori.addItem("Ice");
        dropdown_kategori.addItem("Coffe");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeja_field = new javax.swing.JTextField();
        pemesan_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_menu = new javax.swing.JList<>();
        dropdown_kategori = new javax.swing.JComboBox<>();
        pesan = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tanggal_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tempat_radio = new javax.swing.JRadioButton();
        pulang_radio = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        kasir_radio = new javax.swing.JRadioButton();
        qris_radio = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        total_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("YEENZU CAFE");

        jLabel2.setText("No Meja :");

        jLabel3.setText("Pemesan :");

        jLabel4.setText("Kategori :");

        jLabel5.setText("Menu :");

        nomeja_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeja_fieldActionPerformed(evt);
            }
        });

        pemesan_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemesan_fieldActionPerformed(evt);
            }
        });

        list_menu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_menu);

        dropdown_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        dropdown_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_kategoriActionPerformed(evt);
            }
        });

        pesan.setText("pesan");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });

        tambah.setText("tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal :");

        jLabel7.setText("Tipe pemesanan :");

        buttonGroup1.add(tempat_radio);
        tempat_radio.setText("makan ditempat");
        tempat_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempat_radioActionPerformed(evt);
            }
        });

        buttonGroup1.add(pulang_radio);
        pulang_radio.setText("bawa pulang");

        jLabel8.setText("Metode pembayaran :");

        buttonGroup1.add(kasir_radio);
        kasir_radio.setText("Kasir");

        buttonGroup1.add(qris_radio);
        qris_radio.setText("Qris");

        jLabel9.setText("Total :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addGap(0, 157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pemesan_field, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(dropdown_kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tanggal_field)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nomeja_field, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65))
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tempat_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pulang_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kasir_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(qris_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pesan))
                            .addComponent(total_field, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeja_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tanggal_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pemesan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tempat_radio)
                            .addComponent(pulang_radio))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kasir_radio)
                            .addComponent(qris_radio))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(total_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambah)
                            .addComponent(pesan)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dropdown_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pemesan_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemesan_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemesan_fieldActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String menu =(String) list_menu.getSelectedValue();
        if (list_menu.getSelectedValue() != null) {
        String menuPilihan = list_menu.getSelectedValue().toString();

        String[] potong = menuPilihan.split(" - ");
        String namaMenu = potong[0];
        int harga = Integer.parseInt(potong[1].trim().replace(".", ""));

        daftar_pesanan += "- " + namaMenu + " (Rp " + harga + ")\n";
        totalSemua += harga; 
        total_field.setText(String.valueOf(totalSemua));
        
        JOptionPane.showMessageDialog(this, namaMenu + " berhasil ditambah!");
    } else {
        JOptionPane.showMessageDialog(this, "Pilih menu dulu!");
    }
    }//GEN-LAST:event_tambahActionPerformed

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        try {
        String nomeja = nomeja_field.getText();
        String tanggal = tanggal_field.getText();
        String pemesan = pemesan_field.getText();
        
        String tipePesan = "";
        if (tempat_radio.isSelected()) {
            tipePesan = "Makan di tempat";
        } else if (pulang_radio.isSelected()) {
            tipePesan = "Bawa pulang";
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Tipe Pemesanan dulu!");
            return;
        }
        
        String metodeBayar = "";
        if (kasir_radio.isSelected()) {
            metodeBayar = "Bayar di Kasir";
        } else if (qris_radio.isSelected()) {
            metodeBayar = "QRIS / Cashless";
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Metode Pembayaran dulu!");
            return;
        }
        
        if (daftar_pesanan.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Keranjang kosong! Klik 'Tambah' pada menu dulu.");
            return;
        }

        String ringkasan = "=== YEENZU CAFE ===\n"
                + "Tanggal : " + tanggal + "\n"
                + "Nama    : " + pemesan + "\n"
                + "No Meja : " + nomeja + "\n"
                + "Tipe    : " + tipePesan + "\n"
                + "Bayar   : " + metodeBayar + "\n"
                + "----------------------------\n"
                + daftar_pesanan 
                + "----------------------------\n"
                + "TOTAL BAYAR : Rp " + totalSemua;

        javax.swing.JOptionPane.showMessageDialog(this, ringkasan);

        daftar_pesanan = ""; 
        totalSemua = 0;
        total_field.setText("");
        pemesan_field.setText("");
        nomeja_field.setText("");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memproses pesanan.");
    }
        
        
    }//GEN-LAST:event_pesanActionPerformed

    private void dropdown_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_kategoriActionPerformed
        String kategori = dropdown_kategori.getSelectedItem().toString();
        String[] data = null;

        if (kategori.equals("Makanan")) {
            data = new String[]{"Spagetti Boglonese - 15000", "Bakmie Ayam - 15000", "Nasi Goreng - 15000", "Nasi Ayam Kecombrang - 15000"};
        } else if (kategori.equals("Snack")) {
            data = new String[]{"Kentang goreng - 10000", "Mix platter - 10000", "Dimsum - 10000", "Waffel - 10000", "Risol mayo - 10.000 "};
        } else if (kategori.equals("Ice")) {
            data = new String[]{"Lemon tea - 10000", "Thai tea - 10000", "Matcha - 10000", "Mojito - 10000"};
        } else if (kategori.equals("Coffe")) {
            data = new String[]{"Americano - 10000", "Tubruk - 8000", "Ijo - 8000", "Kopsu ori - 15000", "Kopsu aren - 15000"};
        }

        list_menu.setListData(data);
    }//GEN-LAST:event_dropdown_kategoriActionPerformed

    private void nomeja_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeja_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeja_fieldActionPerformed

    private void tempat_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempat_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempat_radioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pertemuan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pertemuan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pertemuan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pertemuan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pertemuan6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> dropdown_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton kasir_radio;
    private javax.swing.JList<String> list_menu;
    private javax.swing.JTextField nomeja_field;
    private javax.swing.JTextField pemesan_field;
    private javax.swing.JButton pesan;
    private javax.swing.JRadioButton pulang_radio;
    private javax.swing.JRadioButton qris_radio;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tanggal_field;
    private javax.swing.JRadioButton tempat_radio;
    private javax.swing.JTextField total_field;
    // End of variables declaration//GEN-END:variables
}
